<%= ERB.new(File.read(File.expand_path('.kitchen.ec2.attributes.yml'))).result %>

platforms:
# Talk to the Engineering Services team if you need access to the Solaris development infra.
<%
{
  'solaris-11-i86pc' => {
    global_zone_hostname: 'virtsol01.chef.co',
    master_zone_ip:       '172.31.9.84',
    test_zone_ip:         '172.31.9.85',
    brand:                'solaris'
  },
  'solaris-10-i86pc' => {
    global_zone_hostname: 'virtsol02.chef.co',
    master_zone_ip:       '172.31.9.36',
    test_zone_ip:         '172.31.9.37',
    brand:                'native'
  },
  'solaris-11-sun4v' => {
    global_zone_hostname: 'virtsol05.chef.co',
    master_zone_ip:       '172.31.9.60',
    test_zone_ip:         '172.31.9.62',
    brand:                'solaris'
  },
  'solaris-10-sun4v' => {
    global_zone_hostname: 'virtsol05.chef.co',
    master_zone_ip:       '172.31.9.12',
    test_zone_ip:         '172.31.9.13',
    brand:                'solaris10'
  },
}.each_pair do |platform_name, options| %>
  - name: <%= platform_name %>
    provisioner:
      sudo_command: <%= platform_name =~ /solaris-10/ ? '/usr/local/bin/sudo -E' : 'sudo -E' %>
    verifier:
      sudo_command: <%= platform_name =~ /solaris-10/ ? '/usr/local/bin/sudo -E' : 'sudo -E' %>
    driver:
      name: zone
      global_zone_hostname: <%= options[:global_zone_hostname] %>
      global_zone_password: <%= ENV['KITCHEN_ZONE_GLOBAL_ZONE_PASSWORD'] %>
      master_zone_name: <%= platform_name =~ /solaris-10-sun4v/ ? 's10-kitchen-master' : 'kitchen-master' %>
      brand: <%= options[:brand] %>
      master_zone_ip: <%= options[:master_zone_ip] %>
      # TODO: Assign ipaddresses automatically
      test_zone_ip: <%= options[:test_zone_ip] %>
    attributes:
      <<: *ec2_attributes
<% end %>
