source 'https://rubygems.org'


# Install omnibus
gem 'omnibus', github: ENV.fetch('OMNIBUS_GITHUB_REPO', 'chef/omnibus'), branch: ENV.fetch('OMNIBUS_GITHUB_BRANCH', 'master')

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', github: ENV.fetch('OMNIBUS_SOFTWARE_GITHUB_REPO', 'chef/omnibus-software'), branch: ENV.fetch('OMNIBUS_SOFTWARE_GITHUB_BRANCH', 'master')

gem 'artifactory'
