steps:
  - command: "scripts/build.sh"
    label: "build stage"
    agents:
      - "queue=default"
    plugins:
      docker#v1.1.1:
        image: "scotthain/seabass:latest-rhel-7-build"
        # image: "ubuntu:14.04"

  - wait