steps:
  - command: "scripts/build_ubuntu.sh"
    label: "build stage"
    agents:
      - "queue=default"
    plugins:
      docker#v1.1.1:
        # image: "ubuntu:14.04"
        image: "shain/seabass:latest-ubuntu1404-build"

  - wait