# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: harmony

product_key: harmony

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: releng-notify

# Configures github to delete the PR branch to delete after merged to main and
# enable Expire Cache PR label to trigger Omnibus build with Expire Cache
github:
  delete_branch_on_merge: true

pipelines:
  - verify:
      description: Pull Request validation tests
  - omnibus/adhoc:
      definition: .expeditor/adhoc.omnibus.yml
      env:
        - ADHOC: true
  - omnibus/adhoc-expire-cache:
      definition: .expeditor/adhoc.omnibus.yml
      env:
        - ADHOC: true
        - EXPIRE_CACHE: true
  - omnibus/adhoc-canary:
      canary: true
      definition: .expeditor/adhoc-canary.omnibus.yml
      env:
        - ADHOC: true
  - omnibus/release
  - habitat/build:
      canary: true  
      env:
        - ADHOC: true  

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - trigger_pipeline:omnibus/adhoc:
          ignore_labels:
            - "Expeditor: Skip Omnibus"
            - "Expeditor: Skip All"
      #- trigger_pipeline:omnibus/release
  - workload: pull_request_merged:chef/omnibus-software:main:*
    actions:
      - trigger_pipeline:omnibus/adhoc-expire-cache
