# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: harmony

# product_key: harmony

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: releng-notify

artifact_channels:
  - unstable
  # - dev
  # - acceptance
  # - current
  - stable

rubygems:
  - OmnibusHarmony-Test-Gem

# Configures github to delete the PR branch to delete after merged to main and
# enable Expire Cache PR label to trigger Omnibus build with Expire Cache
github:
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Version Major"

pipelines:
  - verify:
      description: Pull Request validation tests
  # - omnibus/adhoc:
  #     definition: .expeditor/adhoc.omnibus.yml
  #     env:
  #       - ADHOC: true
  # - omnibus/adhoc-expire-cache:
  #     definition: .expeditor/adhoc.omnibus.yml
  #     env:
  #       - ADHOC: true
  #       - EXPIRE_CACHE: true
  # - omnibus/adhoc-canary:
  #     canary: true
  #     definition: .expeditor/adhoc-canary.omnibus.yml
  #     env:
  #       - ADHOC: true
  # - omnibus/release
  - habitat/build:
      definition: .expeditor/build.habitat.yml
  - habitat/export:
      definition: .expeditor/habitat-export.pipeline.yml
  - hab-export:
      definition: .expeditor/hab-export-pipeline.yml

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
          ignore_labels:
            - "Expeditor: Skip All"
            - "Expeditor: Skip Version Bump"
      # - trigger_pipeline:omnibus/adhoc:
      #     ignore_labels:
      #       - "Expeditor: Skip Omnibus"
      #       - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"
      - built_in:build_gem:
          only_if: built_in:bump_version
  

# this is the only way currently to promote built-in rubygems publish
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:publish_rubygems
      - built_in:promote_habitat_packages


  # # Automatically promote the Habitat packages from unstable to dev upon successful build
  # - workload: buildkite_hab_build_group_published:{{agent_id}}:*
  #   actions:
  #     - built_in:promote_habitat_packages

#  # Once habitat package is promoted to dev, run the promote script
#   - workload: hab_package_published:dev:chef-demo/hello-omnibus-harmony/{{version_constraint}}
#     actions:
#     - bash:.expeditor/scripts/promote-hab-pkgs.sh:
#         post_commit: true

#   # subscription hab_dev_promote fire off acceptance
#   - workload: staged_workload_released:{{agent_id}}:hab_dev_promote:*
#     actions:
#     - bash:.expeditor/scripts/promote-hab-pkgs.sh:
#         post_commit: true

#   # subscription hab_acceptance_promote fire off promote to current
#   - workload: staged_workload_released:{{agent_id}}:hab_acceptance_promote:*
#     actions:
#     - bash:.expeditor/scripts/promote-hab-pkgs.sh:
#         post_commit: true  

#   # subscription hab_acceptance_promote fire off promote to stable
#   - workload: staged_workload_released:{{agent_id}}:hab_current_promote:*
#     actions:
#     - bash:.expeditor/scripts/promote-hab-pkgs.sh:
#         post_commit: true

#   # this workload should fire off when hab_current_promote:* fires off
#   - workload: hab_package_published:stable:chef-demo/hello-omnibus-harmony/{{version_constraint}}
#     actions:
#       - trigger_pipeline:habitat/export

# staging_areas:
#   - hab_dev_promote:
#       workload: hab_package_published:dev:chef-demo/hello-omnibus-harmony/{{version_constraint}}
#   - hab_acceptance_promote:
#       workload: staged_workload_released:{{agent_id}}:hab_dev_promote:*
#   - hab_current_promote:
#       workload: staged_workload_released:{{agent_id}}:hab_acceptance_promote:*

  # # Subscribe to the promotion of the dev channel to acceptance
  # - workload: project_promoted:{{agent_id}}:dev:*
  #   actions:
  #     - built_in:promote_habitat_packages
  
  # # Subscribe to the promotion of the acceptance channel to current
  # - workload: project_promoted:{{agent_id}}:acceptance:*
  #   actions:
  #     - built_in:promote_habitat_packages

  # # Subscribe to the promotion of the acceptance channel to stable then promote rubygems as well
  # - workload: project_promoted:{{agent_id}}:current:*
  #   actions:
  #     - built_in:promote_habitat_packages




# Subscribe to the promotion of the stable channel then do the s3 publish
  # - workload: hab_package_published:stable:chef-demo/hello-omnibus-harmony/1*
  #   actions:
  #     - trigger_pipeline:habitat/export
  # - workload: pull_request_merged:chef/omnibus-software:main:*
  #   actions:
  #     - trigger_pipeline:omnibus/adhoc-expire-cache:
