# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: harmony

# product_key: harmony

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: releng-notify

artifact_channels:
  - unstable
  # - dev
  # - acceptance
  - stable

rubygems:
  - OmnibusHarmony-Test-Gem

# Configures github to delete the PR branch to delete after merged to main and
# enable Expire Cache PR label to trigger Omnibus build with Expire Cache
github:
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Version Major"

pipelines:
  - verify:
      description: Pull Request validation tests
  # - omnibus/adhoc:
  #     definition: .expeditor/adhoc.omnibus.yml
  #     env:
  #       - ADHOC: true
  # - omnibus/adhoc-expire-cache:
  #     definition: .expeditor/adhoc.omnibus.yml
  #     env:
  #       - ADHOC: true
  #       - EXPIRE_CACHE: true
  # - omnibus/adhoc-canary:
  #     canary: true
  #     definition: .expeditor/adhoc-canary.omnibus.yml
  #     env:
  #       - ADHOC: true
  # - omnibus/release
  - habitat/build:
      definition: .expeditor/build.habitat.yml
  - habitat/export:
      definition: .expeditor/habitat-export.pipeline.yml
  - hab-export:
      definition: .expeditor/hab-export-pipeline.yml

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - built_in:update_changelog:
        ignore_labels:
         - "Expeditor: Skip All"
         - "Expeditor: Skip Changelog"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
          ignore_labels:
            - "Expeditor: Skip All"
            - "Expeditor: Skip Version Bump"
      # - trigger_pipeline:omnibus/adhoc:
      #     ignore_labels:
      #       - "Expeditor: Skip Omnibus"
      #       - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"
      - built_in:build_gem:
          only_if: built_in:bump_version
      # - built_in:promote_habitat_packages:
      #     only_if: built_in:bump_version

  # Automatically promote the Habitat packages from unstable to dev upon successful build
  # - workload: buildkite_hab_build_group_published:{{agent_id}}:*
  #   actions:
  #     - built_in:promote_habitat_packages

# this is the only way currently to promote built-in rubygems publish
  - workload: project_promoted:{{agent_id}}:*
    actions:
      # - built_in:promote_habitat_packages # temporarily disable this to test .rc tag for gem publish
      - built_in:publish_rubygems_chef
      # - built_in:publish_rubygems


  # subscription to fire off any other promotions that you may need for an additional channnel like LTS or something.
  # - workload: staged_workload_released:{{agent_id}}:hab_unstable_promote:*
  #   actions:
  #   - trigger_pipeline:habitat/export:
  #       post_commit: true
  #   - bash:.expeditor/scripts/promote-hab-pkgs.sh:
  #       post_commit: true


# staging_areas:
#   - hab_unstable_promote:
#       workload: hab_package_published:acceptance:chef-demo/hello-omnibus-harmony/{{version_constraint}}
