# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: harmony

product_key: harmony

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: releng-notify


rubygems:
  - omnibus-harmony

# Configures github to delete the PR branch to delete after merged to main and
# enable Expire Cache PR label to trigger Omnibus build with Expire Cache
github:
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Version Major"

artifact_channels:
  - dev
  # - acceptance
  # - current
  # - stable

pipelines:
  - verify:
      description: Pull Request validation tests
  - omnibus/adhoc:
      definition: .expeditor/adhoc.omnibus.yml
      env:
        - ADHOC: true
  - omnibus/adhoc-expire-cache:
      definition: .expeditor/adhoc.omnibus.yml
      env:
        - ADHOC: true
        - EXPIRE_CACHE: true
  - omnibus/adhoc-canary:
      canary: true
      definition: .expeditor/adhoc-canary.omnibus.yml
      env:
        - ADHOC: true
  - omnibus/release
  - habitat/build:
      definition: .expeditor/build.habitat.yml

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
          ignore_labels:
            - "Expeditor: Skip All"
            - "Expeditor: Skip Version Bump"
      # - trigger_pipeline:omnibus/adhoc:
      #     ignore_labels:
      #       - "Expeditor: Skip Omnibus"
      #       - "Expeditor: Skip All"
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"
      - built_in:build_gem:
          only_if: built_in:bump_version
  # Automatically promote the Habitat packages from unstable to dev upon successful build
  # - workload: buildkite_hab_build_group_published:{{agent_id}}:*
  #   actions:
  #     - built_in:promote_habitat_packages

  # # Subscribe to the promotion of the dev channel to acceptance
  # - workload: project_promoted:{{agent_id}}:dev:*
  #   actions:
  #     - built_in:promote_habitat_packages
  
  # # Subscribe to the promotion of the acceptance channel to current
  # - workload: project_promoted:{{agent_id}}:acceptance:*
  #   actions:
  #     - built_in:promote_habitat_packages

  # # Subscribe to the promotion of the acceptance channel to stable then promote rubygems as well
  # - workload: project_promoted:{{agent_id}}:current:*
  #   actions:
  #     - built_in:promote_habitat_packages

  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:publish_rubygems
      - built_in:promote_habitat_packages

  # - workload: hab_package_published:stable:chef-demo/hello-omnibus-harmony/1*
  #   actions:
  #     - built_in:publish_rubygems
      #- trigger_pipeline:omnibus/release
  # - workload: pull_request_merged:chef/omnibus-software:main:*
  #   actions:
  #     - trigger_pipeline:omnibus/adhoc-expire-cache:
